id: I6BE6CC65
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:39:03+00:00'
last_modified: '2022-06-08T05:15:17.634093+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6082
  title: རྩེད་ཆས་ཀུན་དགའ་ནོར་བུའི་བང་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    213C:
      image_group_id: I1KG6275
      title: Volume 1 of rtsed chas kun dga' nor bu'i bang mdzod
      total_pages: 724
      order: 1
      base_file: 213C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
